export const GET_CATEGORIES ='GET_CATEGORIES';
export const NO_CATEGORIES ='NO_CATEGORIES';


export const GET_PRODUCTS_BY_CATEGORIES='GET_PRODUCTS_BY_CATEGORIES';
export const NO_PRODUCTS_BY_CATEGORIES='NO_PRODUCTS_BY_CATEGORIES';